default_config:
lovelace:
  mode: yaml
demo:

sensor:
  - type: custom:entur-card
    name: Rutetider
    show_clock: true
    show_next: true
    show_human: true
    show_extra_departures: true
    entities:
      - entity: sensor.transport_studentersamfundet
        name: Studentersamfundet
        destination: Halstein Gård
      - entity: sensor.transport_trondheim_s_platform_4
        name: Trondheim Sentralbanestasjon
      - entity: sensor.transport_trondheim_lufthavn
        name: Trondheim lufthavn